### ISSUE TITLE
Request for clarification of the benchmark.

### ISSUE THREAD

**Issue by lortonx** [emilpriver/go-rust-bun-node#2]
Hello!
 First of all, thank you very much for your benchmark, it’s an interesting experience! I would like to ask you to add to Node tests using the uWebsockets.js library. This is faster than the standard HTTP node library. uWebsockets is one of the reasons why I don't switch to Bun. I'm sure many people will be interested in this. Thank you!

https://github.com/uNetworking/uWebSockets.js/

**Comment by shivamsingha** [comment]
Bun literally uses uWebSockets

**Comment by lortonx** [comment]
> Bun literally uses uWebSockets

Then, if uWebsockets are taken away from Bun, will the performance be equal to Node?
Or if uWebsockets are added to Node, will the performance be equal again? Maybe even faster? I hope there will be an addition to the tests soon.


By the way, Habr is a big garbage dump .

**Comment by emilpriver** [comment]
Hey :D, Glad you liked it.
I am working on some improvements on the test/benchmark. I have websockets in my backlog and will keep this issue in mind when working on WebSocket test.

**Comment by emilpriver** [comment]
I'm closing this. Feel free to open again if needed.
